### ISSUE TITLE
Update module 7: Construction and Design

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/rse-course#90]
These changes will be coordinated by @jack89roberts 

## General (applicable to every module)
- [x] Make each module independent of earlier ones (ie. do not rely on examples/specific code from earlier modules)
- [ ] Ensure that each module has some small exercises (say 1x 5 min exercise per 45 mins or teaching)
- [x]  add a larger (optional) exercise per course for attendees to complete in their own time
- [x] Update to use more modern libraries and tools (eg. pandas/scipy/numba/poetry)
- [ ] Add instructions to the notebooks that you should "Take 5 minutes to do this exercise"
- [ ] Add estimated timing information at the top of each notebook
- [x] Switch to a colourblind-friendly colour scheme throughout
- [x] What do *you* wish people had told you about Python/coding in general?

## Module 7: Construction and Design
- [x] Ran out of time for participants to meaningfully do anything on the refactoring exercise. **Decision:** Made patterns notebook optional/advanced to indicate it may not be covered, but have added more on linters so may need to cut further material in future. Flipped classroom model should ensure time for exercise.
- [x] Update `__init__` definition (see #72)
- [x] Remove some `assert`s (see #72)
- [x] Boids refactoring exercise had changes that broke tests. New version in this repo (and [PR #80](https://github.com/alan-turing-institute/rse-course/pull/80))
- [x] A lot of good reference material in the module (e.g. ideas for refactorings, different OOP concepts) but not sure how well it translates into teaching. Felt a bit like reading a long list. **Decision:** I'm not sure how to get around this, maybe something that will also work better in flipped classroom model. Perhaps to consider again after next delivery.
- [x] Add discussion on type-hinting (see #37)
- [x] Consider replacing Hungarian Notation with a simple name + type hint.
- [x] Discuss standard library types and encouraging student to also type-hint `Boid` to see the usefulness of it in practice. as part of their refactoring of the `Boid` class.

### Questions from participants included:
- [x] Translating research/user requirements into software - could be a topic to add somewhere in the course. I ended up linking to Module 1 of the RDS course which has some discussion on scoping etc. for data science projects. **Decision:** Nothing added.
- [x] How to verify refactoring doesn't change results (testing)? **Decision:** More extensive linters section and bad boids exercise.
- [x] Recommendations for/possible caveats with using linters (Proposal: Split linters into new notebook, have a more opinionated recommendation). **Decision:** More extensive linters section.
- [x] Inheriting from multiple classes. **Decision:** Beyond scope but can point to multiple inheritance if asked.
- [x] General questions about understanding what functions did, understanding scope etc. **Decision:** Keep in mind, may be something to clarify in other modules.
